<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>${artifactId}</artifactId>

    <parent>
        <groupId>${groupId}</groupId>
        <artifactId>${mainProjectArtifactId}-parent</artifactId>
        <version>${version}</version>
        <relativePath>../parent/pom.xml</relativePath>
    </parent>

    <dependencies>
        <!-- Enable this dependency if the module has `@QuarkusTest`s and uses the JaCoCo build plugin below. -->
        <!-- <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jacoco</artifactId>
            <scope>test</scope>
        </dependency> -->
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
            </plugin>
            <!-- Enable this build plugin to measure test coverage with JaCoCo. -->
            <!-- <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
            </plugin> -->
            <!-- Enable this build plugin if Quarkus should scan this module for beans. -->
            <!-- <plugin>
                <groupId>io.smallrye</groupId>
                <artifactId>jandex-maven-plugin</artifactId>
            </plugin> -->
        </plugins>
    </build>
</project>