<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <artifactId>quarkus-project-structure-distribution-worker</artifactId>
  <packaging>quarkus</packaging>

  <parent>
    <groupId>org.opencastproject</groupId>
    <artifactId>quarkus-project-structure-parent</artifactId>
    <version>1.0-SNAPSHOT</version>
    <relativePath>../../modules/parent/pom.xml</relativePath>
  </parent>

  <dependencies>
    <!-- Dependent API projects are imported automatically -->
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>quarkus-project-structure-common-service-impl</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>quarkus-project-structure-worker-specific-service-impl</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <extensions>true</extensions>
      </plugin>
    </plugins>
  </build>
</project>
